apiVersion: v1
kind: Pod
metadata:
  name: short-app
  labels:
    components: frontend
  spec:
    - name: short-app
      image: antonlarichev/short-app:latest
      ports:
        - containerPort: 80
      resourses:
        limits:
          memory: "128Mi"
          cpu: "1000m"

